name: ODA
on:
  push:
    branches:
      - master
      - smoke/*
      - work/oda

# cancel older workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  oda:
    runs-on: ubuntu-22.04
    timeout-minutes: 50
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
    - name: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: pyvista/setup-headless-display-action@v1
    - run: |
        wget -q https://download.opendesign.com/guestfiles/Demo/ODAFileConverter_QT5_lnxX64_8.3dll_25.5.deb
        sudo add-apt-repository -y ppa:linuxuprising/libpng12
        sudo apt update
        sudo apt-get -y install libpng12-0 qt5dxcb-plugin
        sudo dpkg -i ODAFileConverter_QT5_lnxX64_8.3dll_25.5.deb
        cd /usr/lib/x86_64-linux-gnu
        sudo ln -s libxcb-util.so.1 libxcb-util.so.0
    - run: |
        export QT_DEBUG_PLUGINS=1
        ODAFileConverter test/test-data . ACAD2000 DXF 0 0 example_2000.dwg || true
        test -f example_2000.dxf || (cat example_2000.dxf.err; exit 1)
        echo ODAFileConverter works ok
        export QT_DEBUG_PLUGINS=
    - run: sh autogen.sh
    - run: CFLAGS=-O0 ./configure --disable-bindings
    - run: make -j
    - run: make -j check -C programs TESTS=json.test
      # this makes it green, but we want it red
      #continue-on-error: true
